import { Inter, Space_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const spaceMono = Space_Mono({ 
  weight: ['700'],
  subsets: ["latin"],
  variable: '--font-space-mono'
});

export const metadata = {
  title: "HackOps-StackIt",
  description: "Generated by Team HackOps",
  keywords: "StackIt, Odoo, HackOps",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
    other: "/android-chrome-192x192.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${spaceMono.variable} bg-grid-pattern min-h-screen`}
      >
        <Providers>
          <Navbar/>
          <div className="pt-24">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
