import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "HackOps-StackIt",
  description: "Generated by Team HackOps",
  keywords: "StackIt, Odoo, HackOps",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
    other: "/android-chrome-192x192.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-grid-pattern antialiased`}
      >
        <Providers>
          <Navbar/>
          <div className="pt-24">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
